site_name: "misaka's note"
theme:
  name: material
  language: zh
  palette:
    primary: indigo  # 浙大蓝调
    accent: indigo
  features:
    - navigation.tabs
    - content.code.copy

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:

# 这里的导航栏会自动对应你的 md 文件
nav:
  - Home page: index.md
  - Research notes: 
    - mof-bfn: 
      - Overview: research/mof-bfn/first-paper.md
      - 3-2-repo: research/mof-bfn/3-2-repo.md